name: Deploy MLflow Model

on:
  workflow_dispatch: # Enables manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run build_docker_image.py
      run: python code/build_docker_image.py

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME="davesamer/churn_prediction_model_online"
        docker build -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:latest

    - name: Deploy new Docker image to Azure VM
      env:
        AZURE_VM_USER: ${{ secrets.AZURE_VM_USER }}
        AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
        AZURE_VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
      run: |
        sshpass -p $AZURE_VM_PASSWORD ssh -o StrictHostKeyChecking=no $AZURE_VM_USER@$AZURE_VM_IP << EOF
          docker pull davesamer/churn_prediction_model_online:latest
          docker stop mlflow_container || true
          docker rm mlflow_container || true
          docker run -d --name mlflow_container -p 5000:5000 davesamer/churn_prediction_model_online:latest
        EOF
