name: Automate Process

on:
  push:
    branches:
      - master

jobs:
  automate_process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run feature retrieval script
      run: python code/feature_retrieval.py

    - name: Run feature validation script
      run: python code/feature_validation.py

    - name: Run model training script
      run: python code/model_training.py

    - name: Run model validation script
      run: python code/model_validation.py

